# frozen_string_literal: true

require_relative "pray/version"
require_relative "pray/error"
require_relative "pray/literal"
require_relative "pray/statement_surface"
require_relative "pray/substitute"
require_relative "pray/hashing"
require_relative "pray/constraint"
require_relative "pray/manifest_json"
require_relative "pray/destination"
require_relative "pray/manifest"
require_relative "pray/format_serialize"
require_relative "pray/format_manifest"
require_relative "pray/package_spec"
require_relative "pray/package_spec_version"
require_relative "pray/local_prayer"
require_relative "pray/lockfile"
require_relative "pray/distribution"
require_relative "pray/torrent_manifest"
require_relative "pray/serve_range"
require_relative "pray/apply_report"
require_relative "pray/config"
require_relative "pray/dotenv"
require_relative "pray/project_context"
require_relative "pray/environment"
require_relative "pray/resolve_context"
require_relative "pray/resolve_source"
require_relative "pray/resolve_exports"
require_relative "pray/dependency_graph"
require_relative "pray/resolve_deps"
require_relative "pray/resolve_tarball"
require_relative "pray/invocation"
require_relative "pray/git_refresh"
require_relative "pray/resolve"
require_relative "pray/resolve_local"
require_relative "pray/upstream"
require_relative "pray/upstream_merge"
require_relative "pray/package_spec_render"
require_relative "pray/upstream_refresh"
require_relative "pray/upstream_drift"
require_relative "pray/upstream_latest"
require_relative "pray/compose_dest"
require_relative "pray/render_patch"
require_relative "pray/render_content"
require_relative "pray/render_managed"
require_relative "pray/render"
require_relative "pray/render_dest"
require_relative "pray/transaction"
require_relative "pray/render_layout"
require_relative "pray/verify_position"
require_relative "pray/verify_provisioned"
require_relative "pray/verify"
require_relative "pray/verify_locked_dest"
require_relative "pray/resource_limits"
require_relative "pray/http_body"
require_relative "pray/registry_install"
require_relative "pray/registry_integrity"
require_relative "pray/registry"
require_relative "pray/archive_unpack"
require_relative "pray/archive"
require_relative "pray/plan"
require_relative "pray/git_sources"
require_relative "pray/publish"
require_relative "pray/serve"
require_relative "pray/session"
require_relative "pray/auth_client"
require_relative "pray/confess"
require_relative "pray/sync"
require_relative "pray/trust"
require_relative "pray/materialize"

class << Pray
  public :parse_manifest, :read_manifest_text, :format_package_declaration, :replace_package_declaration,
    :parse_package_spec, :parse_lockfile, :read_lockfile, :serialize_lockfile, :lockfile_hash,
    :write_lockfile, :write_lockfile_if_changed, :lockfiles_equivalent?, :build_lockfile,
    :resolve_project, :render_project, :materialize_project,
    :inspect_project, :inspect_locked_destinations, :verify_project, :drift_project,
    :default_manifest_path, :default_lockfile_path, :project_root_from_manifest
end
